'use client'

import { useState } from 'react'
import { supabase } from '@/lib/supabase'
import { toast } from 'react-hot-toast'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface OrderItem {
  id: string
  productName: string
  currentCount: number
  parLevel: number
  orderQty: number
  distributor?: string
}

interface GenerateOrderModalProps {
  orderType: 'liquor' | 'beer' | 'wine' | 'pepsi' | 'glassware'
  items: OrderItem[]
  distributorName?: string
  userId: string
  userName: string
  onClose: () => void
}

export default function GenerateOrderModal({
  orderType,
  items,
  distributorName,
  userId,
  userName,
  onClose,
}: GenerateOrderModalProps) {
  const [isSending, setIsSending] = useState(false)
  const [orderSent, setOrderSent] = useState(false)

  const orderItems = items.filter(item => item.orderQty > 0)
  const totalItems = orderItems.reduce((sum, item) => sum + item.orderQty, 0)

  const generatePDF = () => {
    const doc = new jsPDF()
    const now = new Date()
    const dateStr = now.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })
    const timeStr = now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
    })

    // Header
    doc.setFontSize(24)
    doc.setFont('helvetica', 'bold')
    doc.text('BSH ORDER', 105, 20, { align: 'center' })

    doc.setFontSize(14)
    doc.setFont('helvetica', 'normal')
    doc.text(`${orderType.toUpperCase()}${distributorName ? ` - ${distributorName}` : ''}`, 105, 30, { align: 'center' })

    doc.setFontSize(10)
    doc.text(`Generated: ${dateStr} at ${timeStr}`, 105, 38, { align: 'center' })
    doc.text(`By: ${userName}`, 105, 44, { align: 'center' })

    // Divider line
    doc.setLineWidth(0.5)
    doc.line(20, 50, 190, 50)

    // Table
    const tableData = orderItems.map(item => [
      item.productName,
      item.currentCount.toString(),
      item.parLevel.toString(),
      item.orderQty.toString(),
    ])

    autoTable(doc, {
      startY: 55,
      head: [['Product', 'Current', 'Par', 'ORDER QTY']],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [71, 85, 105], // slate-600
        textColor: 255,
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { cellWidth: 90 },
        1: { cellWidth: 25, halign: 'center' },
        2: { cellWidth: 25, halign: 'center' },
        3: { cellWidth: 35, halign: 'center', fontStyle: 'bold' },
      },
      styles: {
        fontSize: 10,
      },
    })

    // Summary
    const finalY = (doc as any).lastAutoTable.finalY + 10
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(`Total Items to Order: ${totalItems}`, 20, finalY)
    doc.text(`Total Products: ${orderItems.length}`, 20, finalY + 7)

    // Footer
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text('Generated by BSH Inventory System', 105, 285, { align: 'center' })

    return doc
  }

  const handleGenerateAndSend = async () => {
    setIsSending(true)

    try {
      // Generate PDF
      const doc = generatePDF()
      const pdfBlob = doc.output('blob')
      const pdfBase64 = await blobToBase64(pdfBlob)

      // Save order to database
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          created_by: userId,
          order_type: orderType,
          distributor_name: distributorName || null,
          items: orderItems,
          total_items: totalItems,
          status: 'generated',
        })
        .select()
        .single()

      if (orderError) throw orderError

      // Send email to all registered users
      const response = await fetch('/api/send-order-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          orderType,
          distributorName,
          items: orderItems,
          totalItems,
          generatedBy: userName,
          orderId: order.id,
          pdfBase64,
        }),
      })

      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to send emails')
      }

      const result = await response.json()

      // Update order with email sent info
      await supabase
        .from('orders')
        .update({
          status: 'sent',
          email_sent_at: new Date().toISOString(),
          email_recipients: result.recipients,
        })
        .eq('id', order.id)

      // Open PDF in new tab
      const pdfUrl = URL.createObjectURL(pdfBlob)
      window.open(pdfUrl, '_blank')

      toast.success(`📧 Order sent to ${result.recipients?.length || 0} people!`)
      setOrderSent(true)

    } catch (error: any) {
      console.error('Order error:', error)
      toast.error(error.message || 'Failed to generate order')
    } finally {
      setIsSending(false)
    }
  }

  const handleDownloadOnly = () => {
    const doc = generatePDF()
    doc.save(`BSH_Order_${orderType}_${new Date().toISOString().split('T')[0]}.pdf`)
    toast.success('📄 PDF downloaded!')
  }

  const blobToBase64 = (blob: Blob): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onloadend = () => {
        const base64 = (reader.result as string).split(',')[1]
        resolve(base64)
      }
      reader.onerror = reject
      reader.readAsDataURL(blob)
    })
  }

  if (orderItems.length === 0) {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6">
          <h2 className="text-xl font-bold text-gray-800 mb-4">✅ No Order Needed</h2>
          <p className="text-gray-600 mb-6">
            All {orderType} items are at or above par level. Nothing to order!
          </p>
          <button
            onClick={onClose}
            className="w-full py-3 bg-slate-600 text-white font-bold rounded-xl hover:bg-slate-700 transition"
          >
            Close
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="bg-gradient-to-r from-slate-600 to-slate-700 text-white p-6">
          <h2 className="text-2xl font-bold">
            📦 {orderType.toUpperCase()} Order
            {distributorName && <span className="font-normal"> - {distributorName}</span>}
          </h2>
          <p className="text-slate-200 mt-1">
            {orderItems.length} products • {totalItems} total units
          </p>
        </div>

        {/* Order Items */}
        <div className="flex-1 overflow-y-auto p-6">
          <table className="w-full">
            <thead className="bg-slate-100 sticky top-0">
              <tr>
                <th className="px-4 py-2 text-left text-sm font-bold text-gray-600">Product</th>
                <th className="px-4 py-2 text-center text-sm font-bold text-gray-600">Current</th>
                <th className="px-4 py-2 text-center text-sm font-bold text-gray-600">Par</th>
                <th className="px-4 py-2 text-center text-sm font-bold text-gray-600">ORDER</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {orderItems.map((item) => (
                <tr key={item.id} className="hover:bg-slate-50">
                  <td className="px-4 py-3 font-medium">{item.productName}</td>
                  <td className="px-4 py-3 text-center text-red-600">{item.currentCount}</td>
                  <td className="px-4 py-3 text-center">{item.parLevel}</td>
                  <td className="px-4 py-3 text-center">
                    <span className="bg-red-100 text-red-700 px-3 py-1 rounded-full font-bold">
                      {item.orderQty}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Actions */}
        <div className="border-t p-6 bg-gray-50">
          {orderSent ? (
            <div className="text-center">
              <div className="text-green-600 text-xl font-bold mb-2">✅ Order Sent!</div>
              <p className="text-gray-600 mb-4">PDF opened in new tab. Emails sent to all team members.</p>
              <button
                onClick={onClose}
                className="px-6 py-3 bg-slate-600 text-white font-bold rounded-xl hover:bg-slate-700 transition"
              >
                Close
              </button>
            </div>
          ) : (
            <div className="flex gap-3">
              <button
                onClick={onClose}
                className="flex-1 py-3 bg-gray-200 text-gray-700 font-bold rounded-xl hover:bg-gray-300 transition"
              >
                Cancel
              </button>
              <button
                onClick={handleDownloadOnly}
                className="flex-1 py-3 bg-slate-500 text-white font-bold rounded-xl hover:bg-slate-600 transition"
              >
                📄 PDF Only
              </button>
              <button
                onClick={handleGenerateAndSend}
                disabled={isSending}
                className="flex-1 py-3 bg-gradient-to-r from-green-500 to-emerald-500 text-white font-bold rounded-xl hover:from-green-600 hover:to-emerald-600 transition disabled:opacity-50"
              >
                {isSending ? '⏳ Sending...' : '📧 Generate & Email All'}
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
