import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

interface OrderItem {
  id: string
  productName: string
  currentCount: number
  parLevel: number
  orderQty: number
  distributor?: string
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { orderType, distributorName, items, totalItems, generatedBy, orderId, pdfBase64 } = body

    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    // Get all registered users' emails
    const { data: profiles, error: profilesError } = await supabase
      .from('profiles')
      .select('email, full_name')
      .not('email', 'is', null)

    if (profilesError) {
      console.error('Error fetching profiles:', profilesError)
    }

    // Resend free plan (onboarding@resend.dev) can only send to account owner
    // Send individually to each recipient so one failure doesn't block others
    const allRecipients = Array.from(new Set([
      'jamie@ledgepipe.com',
      ...(profiles?.map(p => p.email).filter(Boolean) || [])
    ]))

    // Build email HTML
    const itemsHtml = (items as OrderItem[])
      .map(item => `
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${item.productName}</td>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center;">${item.currentCount}</td>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center;">${item.parLevel}</td>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center; font-weight: bold; color: #dc2626;">${item.orderQty}</td>
        </tr>
      `)
      .join('')

    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head><meta charset="utf-8"><title>BSH Order</title></head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #475569, #334155); color: white; padding: 20px; border-radius: 12px 12px 0 0;">
          <h1 style="margin: 0;">📦 BSH Order</h1>
          <p style="margin: 8px 0 0 0; opacity: 0.9;">${orderType.toUpperCase()}${distributorName ? ` - ${distributorName}` : ''}</p>
        </div>
        <div style="background: #f8fafc; padding: 20px; border: 1px solid #e2e8f0; border-top: none;">
          <p style="margin: 0 0 10px 0;">
            <strong>Generated by:</strong> ${generatedBy}<br>
            <strong>Date:</strong> ${new Date().toLocaleString()}<br>
            <strong>Total Items:</strong> ${totalItems} units across ${items.length} products
          </p>
        </div>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          <thead>
            <tr style="background: #475569; color: white;">
              <th style="padding: 12px; text-align: left;">Product</th>
              <th style="padding: 12px; text-align: center;">Current</th>
              <th style="padding: 12px; text-align: center;">Par</th>
              <th style="padding: 12px; text-align: center;">ORDER QTY</th>
            </tr>
          </thead>
          <tbody>${itemsHtml}</tbody>
        </table>
        <div style="margin-top: 20px; padding: 15px; background: #fef2f2; border-radius: 8px; border-left: 4px solid #dc2626;">
          <strong>📋 Action Required:</strong> Please place this order with the supplier.
        </div>
        <p style="margin-top: 30px; color: #6b7280; font-size: 12px; text-align: center;">Generated by BSH Inventory System</p>
      </body>
      </html>
    `

    let emailSent = false

    // Send to each recipient individually (Resend free plan only allows account owner)
    const resendApiKey = process.env.RESEND_API_KEY
    const successfulRecipients: string[] = []

    if (resendApiKey) {
      for (const recipient of allRecipients) {
        try {
          const emailResponse = await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${resendApiKey}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              from: process.env.RESEND_FROM_EMAIL || 'BSH Inventory <onboarding@resend.dev>',
              to: [recipient],
              subject: `📦 BSH Order: ${orderType.toUpperCase()}${distributorName ? ` - ${distributorName}` : ''} (${items.length} items)`,
              html: emailHtml,
            }),
          })

          if (emailResponse.ok) {
            successfulRecipients.push(recipient)
          } else {
            const err = await emailResponse.json()
            console.error(`Resend error for ${recipient}:`, JSON.stringify(err))
          }
        } catch (e) {
          console.error(`Resend exception for ${recipient}:`, e)
        }
      }
    }

    return NextResponse.json({
      success: true,
      recipients: successfulRecipients,
    })

  } catch (error: any) {
    console.error('Send order email error:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to send order email' },
      { status: 500 }
    )
  }
}
