import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

interface OrderItem {
  id: string
  productName: string
  currentCount: number
  parLevel: number
  orderQty: number
  distributor?: string
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { orderType, distributorName, items, totalItems, generatedBy, orderId, pdfBase64 } = body

    // Create admin supabase client to fetch all users
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    // Get all registered users' emails
    const { data: profiles, error: profilesError } = await supabase
      .from('profiles')
      .select('email, full_name')
      .not('email', 'is', null)

    if (profilesError) {
      console.error('Error fetching profiles:', profilesError)
      throw new Error('Failed to fetch user emails')
    }

    const recipients = profiles?.map(p => p.email).filter(Boolean) || []

    if (recipients.length === 0) {
      return NextResponse.json({ error: 'No recipients found' }, { status: 400 })
    }

    // Check if Resend API key is configured
    const resendApiKey = process.env.RESEND_API_KEY

    if (!resendApiKey) {
      console.log('RESEND_API_KEY not configured - logging order instead')
      console.log('Would send order to:', recipients)
      console.log('Order type:', orderType)
      console.log('Items:', items.length)

      // Return success but note that emails weren't actually sent
      return NextResponse.json({
        success: true,
        recipients,
        note: 'Email service not configured - order logged only',
      })
    }

    // Build email HTML
    const itemsHtml = (items as OrderItem[])
      .map(item => `
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${item.productName}</td>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center;">${item.currentCount}</td>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center;">${item.parLevel}</td>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center; font-weight: bold; color: #dc2626;">${item.orderQty}</td>
        </tr>
      `)
      .join('')

    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>BSH Order - ${orderType.toUpperCase()}</title>
      </head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #475569, #334155); color: white; padding: 20px; border-radius: 12px 12px 0 0;">
          <h1 style="margin: 0;">📦 BSH Order</h1>
          <p style="margin: 8px 0 0 0; opacity: 0.9;">
            ${orderType.toUpperCase()}${distributorName ? ` - ${distributorName}` : ''}
          </p>
        </div>

        <div style="background: #f8fafc; padding: 20px; border: 1px solid #e2e8f0; border-top: none;">
          <p style="margin: 0 0 10px 0;">
            <strong>Generated by:</strong> ${generatedBy}<br>
            <strong>Date:</strong> ${new Date().toLocaleString()}<br>
            <strong>Total Items:</strong> ${totalItems} units across ${items.length} products
          </p>
        </div>

        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          <thead>
            <tr style="background: #475569; color: white;">
              <th style="padding: 12px; text-align: left;">Product</th>
              <th style="padding: 12px; text-align: center;">Current</th>
              <th style="padding: 12px; text-align: center;">Par</th>
              <th style="padding: 12px; text-align: center;">ORDER QTY</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHtml}
          </tbody>
        </table>

        <div style="margin-top: 20px; padding: 15px; background: #fef2f2; border-radius: 8px; border-left: 4px solid #dc2626;">
          <strong>📋 Action Required:</strong> Please place this order with the supplier.
        </div>

        <p style="margin-top: 30px; color: #6b7280; font-size: 12px; text-align: center;">
          Generated by BSH Inventory System
        </p>
      </body>
      </html>
    `

    // Send email via Resend
    const emailResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: process.env.RESEND_FROM_EMAIL || 'BSH Inventory <orders@resend.dev>',
        to: recipients,
        subject: `📦 BSH Order: ${orderType.toUpperCase()}${distributorName ? ` - ${distributorName}` : ''} (${items.length} items)`,
        html: emailHtml,
        attachments: pdfBase64 ? [
          {
            filename: `BSH_Order_${orderType}_${new Date().toISOString().split('T')[0]}.pdf`,
            content: pdfBase64,
          }
        ] : undefined,
      }),
    })

    if (!emailResponse.ok) {
      const errorData = await emailResponse.json()
      console.error('Resend error:', errorData)
      throw new Error(errorData.message || 'Failed to send email')
    }

    return NextResponse.json({
      success: true,
      recipients,
    })

  } catch (error: any) {
    console.error('Send order email error:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to send order email' },
      { status: 500 }
    )
  }
}
